config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  devise_for :users do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Home page
  root to: 'pages#home', as: :home

  # about and info page
  get 'about', to: 'pages#about'

  # hoe moet je bestellen pagina
  get 'bestellen', to: 'pages#bestellen', as: :bestellen

  # bekijk het hele assortiment
  get 'assortiment', to: 'pages#assortiment', as: :assortiment

  # stekjes CRUD
  # all stekjes
  get 'stekjes', to: 'stekjes#index', as: :allstekjes

  # create a new stekje
  post 'stekjes', to: 'stekjes#create'
  get 'stekjes/new', to: 'stekjes#new', as: :new

  # edit an existing stekje
  # make the changes
  get 'stekjes/:id/edit', to: 'stekjes#edit', as: :editstekje
  # save the changes made
  patch 'stekjes/:id', to: 'stekjes#update'

  # delete an existing stekje
  delete 'stekjes/:id', to: 'stekjes#destroy'

  # show one stekje
  get 'stekjes/:id', to: 'stekjes#show', as: :stekje

  # show a user's profile
  get 'private_profile', to: 'profiles#private'

  # plantjes category show
  get 'plantjes', to: 'stekjes#plantjes', as: :plantjes
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stekjes
end

app/models/stekje.rb
# frozen_string_literal: true

# stekje model
class Stekje < ApplicationRecord
  has_one_attached :file
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Conntroller
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :sign_out])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# pages controller
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home, :about]

  def about; end

  def home; end

  def bestellen; end

  def assortiment; end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def private; end
end

app/controllers/stekjes_controller.rb
# frozen_string_literal: true

# stekjes controller
class StekjesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @stekjes = Stekje.all
  end

  def new
    @stekje = Stekje.new # needed to instantiate the form_for
    @categories = Category.all.map{ |c| [c.name, c.id ] }
  end

  def create
    # Will raise ActiveModel::ForbiddenAttributesError
    @stekje = Stekje.new(stekje_params)
    @stekje.category_id = params[:category_id]

    if @stekje.save
       redirect_to(@stekje, notice: 'Stekje was succesfully created.')
      else
        render json: stekje.errors, status: :unprocessable_entity
    end
  end

  def edit
    @stekje = Stekje.find(params[:id])
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    @stekje = Stekje.find(params[:id])
    @stetje.category_id = params[:category_id]
    @stekje.update(stekje_params)

    redirect_to stekje_path(@stekje)
  end

  def destroy
    @stekje = Stekje.find(params[:id])
    @stekje.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to allstekjes_path, notice: 'Het stekje is verwijderd'
  end

  def show
    @stekje = Stekje.find(params[:id])
  end

  def plantjes; end

  private

  def stekje_params
    params.require(:stekje).permit(:name, :image, :category, :size,
                                   :description, :price, :care, :instock,
                                   :file, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , class: 'btn btn-success'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Categories</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.description %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
    <p>
    <strong>Name:</strong>
    <%= @category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @category.description %>
  </p>
  <h3> Stekjes under this category </h3>
    <% Stekje.where(category_id: @category.id).each do |stekje| %>
    <div class="card" style="width: 18rem; margin: 20px;">
          <%= image_tag(stekje.file, class:'card-img-top card-images-index', alt:'Card image cap',
              style:'height: 288px;')%>
          <div class="card-body">
            <h5 class="card-title"><%= stekje.name %></h5>
            <p class="card-text"><%= stekje.price %> €</p>
            <%= link_to 'Info', stekje_path(stekje.id), class:'btn btn-success' %>
          </div>
        </div>
    <% end %>

  <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-warning'%> |
  <%= link_to 'Back', categories_path, class: 'btn btn-dark' %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      @import url('https://fonts.googleapis.com/css?family=Marck+Script&display=swap');
    </style>
    <title>Stekjes Atelier</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>



    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%#= render 'layouts/shared/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<div class="containerx">
<h1>Our first view</h1>
<p>
Hallo allemaal!
Zoals jullie allemaal weten ben ik gek op planten.
<br>Nou
heb ik gebruik gemaakt van deze ‘quarantaine dagen’
om daar iets serieuzer mee aan de slag te gaan en is
een kleine business hieruit ontstaan: “Het Stekjes
Atelier”. Ik verkoop allerlei (bĳzondere) plantjes en
stekjes via marktplaats en instagram
(@Het_StekjesAtelier). En hier hoop ik uiteindelĳk een
webshop van de maken!
Dussss mochten jullie op zoek zĳn naar nieuwe
plantjes, een leuk kadotje of nieuwe stekjes/baby
plantjes om zelf op te zien groeien, of iemand kennen
die daar naar opzoek is, stuur mĳ vooral een berichtje
of bekĳk mĳn advertenties!
Zorg goed voor jezelf deze dagen en ik zie jullie snel
weer!
Groetjes,
Emily
Marktplaats: https://www.marktplaats.nl/u/emily-t/
18150603/
Email: info@hetstekjesatelier.nl
Insta: @Het_StekjesAtelier</p>

</div>

app/views/pages/assortiment.html.erb
<div class="container">
<h1> Het assortiemtn wiufvbzdkf</h1>
</div>

app/views/pages/bestellen.html.erb
<h1>Het bestellen werkt</h1>

<p>lorem ipsum</p>

app/views/pages/home.html.erb
<div class="background-home">
  <div class='left-div two-div-home'>
    <h2 class="h2-home">Welkom bij het</h2></br>
    <h1 class="h1-home">Stekjes Atelier</h1>
  </div>
  <div class="right-div two-div-home">
    <!-- div with image to the right-->
    <%= link_to 'Bekijk het assortiment', stekjes_path, class:'btn btn-info' %>
      <% if current_user && current_user.admin %>
      <%= link_to 'Voeg een stekje toe', new_path, class:'btn btn-success' %>
      <% end %>
  </div>
</div>

app/views/profiles/private.html.erb
<div class="container">
  <h1>The profile page works</h1>

  <%= button_to "Edit profile",
</div>

app/views/shared/_flashes.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light background-navbar">
  <%= link_to "Stekjes Atelier", home_path, class: "navbar-brand brand_font" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"aria-expanded="false">
          Assortiment
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a href="/categories/1" class="dropdown-item">Stekjes</a>
            <a href="/categories/2" class="dropdown-item">Planten</a>
            <a href="/categories/3" class="dropdown-item">Zeldzame Planten</a>
          </div>

        </li>
      </li>
      <li class="nav-item">
        <%= link_to 'Bestellen', bestellen_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"aria-expanded="false">
          Account
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", private_profile_path , class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <% if current_user && current_user.admin %>
          <%= link_to 'Categories', categories_path, class: 'nav-link' %>
        <% end %>
      </li>
      </li>

    </ul>

  </div>

</nav>

app/views/stekjes/_form_stekje.html.erb
<%= form_for(@stekje) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter name" %>
  </div>
  <div class="form-group">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>
  <div class="form-group">
    <%= f.label :size %>
    <%= f.number_field :size, class: 'form-control', placeholder: "Enter size" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', placeholder: "Enter plant description" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control', placeholder: "Enter price" %>
  </div>
  <div class="form-group">
    <%= f.label :care %>
    <%= f.number_field :care, in: 1..5, step: 1, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= select_tag(:category_id, options_for_select(@categories), prompt: 'Select one!') %>
  </div>
  <div class="form-group">
    <%= f.label :instock %>
    <%= f.check_box :instock, class: 'form-check-label', placeholder: "Enter care" %>
  </div>
  <%= f.button :submit , class: 'btn btn-success'%>

<% end %>

app/views/stekjes/edit.html.erb
<div class="container">
  <%= render 'form_stekje', stekjes: @stekjes %>
</div>

app/views/stekjes/index.html.erb
<div class="container">
  <h1 class="h1-css-index">Alle stekjes:</h1>
  <div>
    <ul class='arrange_stekjes'>
      <% @stekjes.each do |stekje| %>
        <div class="card" style="width: 18rem; margin: 20px;">
          <%= image_tag(stekje.file, class:'card-img-top card-images-index', alt:'Card image cap',
              style:'height: 288px;')%>
          <div class="card-body">
            <h5 class="card-title"><%= stekje.name %></h5>
            <p class="card-text"><%= stekje.price %> €</p>
            <%= link_to 'Info', stekje_path(stekje.id), class:'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
  <%= link_to 'Terug', home_path, class:'btn btn-dark ' %>
</div>

app/views/stekjes/new.html.erb
<div class="container">
<%= render 'form_stekje', stekjes: @stekjes %>
  <%= link_to 'Terug', home_path, class:'btn btn-warning ' %>
</div>

app/views/stekjes/plantjes.html.erb
<div class="container">
  <h1>
    plantjes werken
  </h1>
</div>

app/views/stekjes/show.html.erb
<div class="container">
  <h1><%= @stekje.name %></h1>
  <p><%= @stekje.category.name %></p>
  <p><%= @stekje.price %></p>
  <p>
    <%= image_tag(@stekje.file) %>
  </p>
  <% if current_user && current_user.admin %>
    <td><%= link_to 'Edit Stekje', editstekje_path(@stekje) %></td>
    <%= button_to 'Remove Stekje', stekje_path(@stekje), method: 'delete', confirm: 'Are you sure?', class:'btn btn-danger' %>
  <% end %>
  <%= link_to 'Terug', home_path, class:'btn btn-warning ' %>
</div>